"""update_config_model_displaytemplatename

Revision ID: f10afed99ce2
Revises: d68f6ca67c9d
Create Date: 2021-09-10 20:29:42.955431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10afed99ce2'
down_revision = 'd68f6ca67c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ConfigTemplate_display_template_name_key', 'ConfigTemplate', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ConfigTemplate_display_template_name_key', 'ConfigTemplate', ['display_template_name'])
    # ### end Alembic commands ###
