"""document_and_config_migration

Revision ID: 47ff5284e01f
Revises: 70abad877c06
Create Date: 2021-09-10 00:14:01.160714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ff5284e01f'
down_revision = '70abad877c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConfigTemplate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('template_name', sa.Text(), nullable=False),
    sa.Column('version_no', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.create_table('ConfigTemplateMetadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_name', sa.Text(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['ConfigTemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ConfigTemplateMetadata')
    op.drop_table('ConfigTemplate')
    # ### end Alembic commands ###
