"""config_model_created

Revision ID: ca3f9590696a
Revises: 41c2dc3956bd
Create Date: 2021-09-09 23:19:12.041468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3f9590696a'
down_revision = '41c2dc3956bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConfigTemplate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('template_name', sa.Text(), nullable=False),
    sa.Column('version_no', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.drop_table('DocCategoryConfigTemplate')
    op.drop_constraint(None, 'ConfigTemplateMetadata', type_='foreignkey')
    op.create_foreign_key(None, 'ConfigTemplateMetadata', 'ConfigTemplate', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ConfigTemplateMetadata', type_='foreignkey')
    op.create_foreign_key(None, 'ConfigTemplateMetadata', 'DocCategoryConfigTemplate', ['template_id'], ['id'])
    op.create_table('DocCategoryConfigTemplate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.TEXT(), nullable=False),
    sa.Column('template_name', sa.TEXT(), nullable=False),
    sa.Column('version_no', sa.TEXT(), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name')
    )
    op.drop_table('ConfigTemplate')
    # ### end Alembic commands ###
