"""updated_config_model

Revision ID: d68f6ca67c9d
Revises: 931e489bc0ed
Create Date: 2021-09-10 15:51:04.739726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68f6ca67c9d'
down_revision = '931e489bc0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ConfigTemplate', sa.Column('display_template_name', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'ConfigTemplate', ['display_template_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ConfigTemplate', type_='unique')
    op.drop_column('ConfigTemplate', 'display_template_name')
    # ### end Alembic commands ###
